Run("notepad.exe")
WinWaitActive("Untitled - Notepad")
Send("Aashish Bansal - 19BIT0346. ")
Send("Theory Assignment for ITE2004 - Software Testing")
WinClose("Untitled - Notepad")
WinWaitActive("Notepad","Save")
Send("!s")
sleep(3000)
Send("autoit automation")
sleep(3000)
Send("!s")